version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: shopping_cart_zookeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka:2.12-2.1.1
    container_name: shopping_cart_kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  postgres:
    image: postgres:latest
    container_name: shopping_cart_postgres
    environment:
      - "TZ=Europe/Amsterdam"
      - "POSTGRES_USER=shopping_cart"
      - "POSTGRES_PASSWORD=shopping_cart"
    ports:
      - "5432:5432"  # credentials (shopping_cart:shopping_cart)
