name: PR Validation

on:
  pull_request:
    branches: [ master ]

env:
  LIGHTBEND_COMMERCIAL_MVN: ${{ secrets.LIGHTBEND_COMMERCIAL_MVN }}
  LIGHTBEND_COMMERCIAL_IVY: ${{ secrets.LIGHTBEND_COMMERCIAL_IVY }}

jobs:

  validate-samples:
    name: ${{ matrix.framework }}/${{ matrix.language }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - language: java
            framework: akka
            command: mvn --no-transfer-progress package test
          - language: scala
            framework: akka
            command: sbt test
          - language: java
            framework: lagom
            command: sbt test
          - language: scala
            framework: lagom
            command: sbt test
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        env:
          cache-name: ${{ matrix.framework }}-dependencies-cache-${{ matrix.language }}
        with:
          path: |
            ~/.m2
            ~/.ivy2/cache
            ~/.sbt
            ~/.cache/coursier/v1
          key: ${{ runner.os }}-${{ matrix.framework }}-${{ env.cache-name }}
      - uses: AdoptOpenJDK/install-jdk@v1
        name: Install AdoptOpenJDK 11
        with:
          version: "11"
      - name: docker-compose up
        run: |
          pushd ${{ matrix.framework }}/shopping-cart-${{ matrix.language }} && docker-compose up -d && popd
          sleep 30
      - name: docker-compose ps
        run: pushd ${{ matrix.framework }}/shopping-cart-${{ matrix.language }} && docker-compose ps && popd
      - name: Run ${{ matrix.command }}
        run: pushd ${{ matrix.framework }}/shopping-cart-${{ matrix.language }} && ${{ matrix.command }} && popd
      - name: docker-compose down
        run: pushd ${{ matrix.framework }}/shopping-cart-${{ matrix.language }} && docker-compose down && popd
