name: Validate Pull Requests

on: [pull_request]

jobs:
  build:
    name: Test ${{ matrix.language }} Samples
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        language: [java, scala]
    steps:
      - uses: actions/checkout@v2
      - name: sbt cache
        uses: actions/cache@v2
        env:
          cache-name: sbt-dependencies-cache
        with:
          path: |
            ~/.ivy2/cache
            ~/.sbt
            ~/.cache/coursier/v1
          key: ${{ runner.os }}-sbt-${{ env.cache-name }}

      - name: Install AdoptOpenJDK 11
        uses: AdoptOpenJDK/install-jdk@v1
        with:
          version: "11"

      - name: Start docker-compose services for lagom/shopping-cart-${{ matrix.language }}
        run: |
          pushd lagom/shopping-cart-${{ matrix.language }} && docker-compose up -d && popd
          sleep 30
      - name: Check docker-compose services for lagom/shopping-cart-${{ matrix.language }}
        run: pushd lagom/shopping-cart-${{ matrix.language }} && docker-compose ps && popd
      - name: Run tests for lagom/shopping-cart-${{ matrix.language }}
        run: pushd lagom/shopping-cart-${{ matrix.language }} && sbt test && popd
        env:
          LIGHTBEND_COMMERCIAL_MVN: ${{ secrets.LIGHTBEND_COMMERCIAL_MVN }}
          LIGHTBEND_COMMERCIAL_IVY: ${{ secrets.LIGHTBEND_COMMERCIAL_IVY }}
      - name: Shutdown docker-compose services for lagom/shopping-cart-${{ matrix.language }}
        run: pushd lagom/shopping-cart-${{ matrix.language }} && docker-compose down && popd
